#!/usr/bin/env node
// JSON Schema -> per-language types for the canonical.cloud API.
//
//   node src/generate.mjs          # write generated/<lang>/...
//   node src/generate.mjs --check  # verify generated files are up to date (CI)
//
// JSON Schema (schema/*.schema.json) is the source of truth. Generated files are
// adapters only — never hand-edit them. Adding a language is one entry in
// EMITTERS; adding a type is one entry in a schema file + schema/index.json.
//
// Hardened: validates the index + every schema, rejects duplicate type names and
// dangling $refs, accepts snake_case domain fields and lowerCamelCase wire fields,
// sanitizes doc comments, raw-escapes Rust keyword fields, and emits typed enums
// for string `enum`s.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const schemaDir = path.join(root, "schema");
const genDir = path.join(root, "generated");

const BANNER = "AUTOGENERATED by src/generate.mjs — do not edit by hand; edit schema/ and regenerate.";

class GenError extends Error {}
const fail = (msg) => { throw new GenError(msg); };

// --- helpers -----------------------------------------------------------------

const oneLine = (s) => String(s || "").replace(/\s+/g, " ").trim();
const pascal = (s) => s.split(/[_\-\s]+/).map((w) => (w ? w[0].toUpperCase() + w.slice(1) : "")).join("");
const snake = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();
const camel = (s) => s.replace(/[_\-]([a-z0-9])/g, (_, c) => c.toUpperCase());
// Comment-escapers so a description can never break the generated file.
const cLine = (s) => oneLine(s);                                  // // and /// and #
const cBlock = (s) => oneLine(s).replace(/\*\//g, "*\\/");        // /** ... */
const pyDoc = (s) => oneLine(s).replace(/"""/g, "'''").replace(/\\/g, "\\\\"); // """ ... """

const RUST_KEYWORDS = new Set([
  "as","break","const","continue","crate","dyn","else","enum","extern","false","fn","for","if","impl",
  "in","let","loop","match","mod","move","mut","pub","ref","return","self","static","struct","super",
  "trait","true","type","unsafe","use","where","while","async","await","box","union",
]);
// Dart reserved words that can never be used as a plain identifier. Contextual
// and built-in identifiers (`await`, `dynamic`, `late`, …) are legal as field
// names, so they are deliberately not listed here.
const DART_KEYWORDS = new Set([
  "assert","break","case","catch","class","const","continue","default","do","else","enum","extends",
  "false","final","finally","for","if","in","is","new","null","rethrow","return","super","switch",
  "this","throw","true","try","var","void","while","with",
]);
const FIELD_RE = /^(?:[a-z][a-z0-9]*(?:_[a-z0-9]+)*|[a-z][A-Za-z0-9]*)$/;

const refName = (s) => (s && s.$ref ? s.$ref.split("/").pop() : null);
const isNullable = (s) => s && Array.isArray(s.type) && s.type.includes("null");
const nonNullSchema = (s) => {
  if (!isNullable(s)) return s;
  const types = s.type.filter((type) => type !== "null");
  return { ...s, type: types.length === 1 ? types[0] : types };
};
const isStringEnum = (s) => {
  const inner = nonNullSchema(s);
  return inner && inner.type === "string" && Array.isArray(inner.enum) && inner.enum.length > 0;
};
const enumTypeName = (typeName, fieldName) => `${typeName}${pascal(fieldName)}`;

// --- load + validate ----------------------------------------------------------

function loadTypes() {
  const indexPath = path.join(schemaDir, "index.json");
  if (!fs.existsSync(indexPath)) fail(`missing ${indexPath}`);
  let index;
  try { index = JSON.parse(fs.readFileSync(indexPath, "utf8")); }
  catch (e) { fail(`schema/index.json is not valid JSON: ${e.message}`); }
  if (!Array.isArray(index.schemas)) fail("schema/index.json must have a `schemas` array");

  const types = [];
  const seen = new Map(); // type name -> source file (duplicate detection)

  for (const file of index.schemas) {
    if (typeof file !== "string" || !file.endsWith(".schema.json")) {
      fail(`schema/index.json entry is not a *.schema.json file: ${JSON.stringify(file)}`);
    }
    const abs = path.join(schemaDir, file);
    if (!fs.existsSync(abs)) fail(`schema/index.json lists ${file} but it does not exist`);
    let doc;
    try { doc = JSON.parse(fs.readFileSync(abs, "utf8")); }
    catch (e) { fail(`${file} is not valid JSON: ${e.message}`); }
    if (!doc.$defs || typeof doc.$defs !== "object") fail(`${file} has no $defs object`);

    for (const [name, def] of Object.entries(doc.$defs)) {
      if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) fail(`${file}: $def name must be PascalCase: ${name}`);
      if (seen.has(name)) fail(`duplicate type name "${name}" in ${file} and ${seen.get(name)}`);
      seen.set(name, file);
      const required = new Set(def.required || []);
      const props = Object.entries(def.properties || {}).map(([pname, pschema]) => {
        if (!FIELD_RE.test(pname)) {
          fail(`${file}:${name}: property "${pname}" must be snake_case or lowerCamelCase (${FIELD_RE})`);
        }
        if (Array.isArray(pschema.type)) {
          const nonNullTypes = pschema.type.filter((type) => type !== "null");
          if (!pschema.type.includes("null") || nonNullTypes.length !== 1) {
            fail(`${file}:${name}.${pname}: only one scalar type plus null is supported`);
          }
        }
        // A null-valued keyword is never valid JSON Schema, and it is worse than
        // a wrong value: `null !== undefined`, so a consumer's `if (rule.pattern
        // !== undefined)` guard still fires and builds `new RegExp(null)`, which
        // silently matches against /null/. src/quote-schema-semantic-merge-guards
        // catches this in CI; rejecting it here also stops `npm run generate`
        // from emitting adapters from a schema that is already invalid.
        for (const [keyword, value] of Object.entries(pschema)) {
          if (value === null) {
            fail(`${file}:${name}.${pname}: keyword "${keyword}" is null; omit the keyword instead`);
          }
        }
        return { name: pname, schema: pschema, required: required.has(pname), description: pschema.description || "" };
      });
      types.push({ name, description: def.description || "", props, source: file });
    }
  }

  // Validate every $ref points at a known type.
  const known = new Set(types.map((t) => t.name));
  for (const t of types) {
    for (const p of t.props) {
      for (const s of [p.schema, p.schema && p.schema.items]) {
        const r = refName(s);
        if (r && !known.has(r)) fail(`${t.source}:${t.name}.${p.name}: $ref to unknown type "${r}"`);
      }
    }
  }
  return types;
}

// Collect distinct enum types referenced by fields (for languages with enums).
function collectEnums(types) {
  const enums = new Map(); // enumName -> values[]
  for (const t of types) {
    for (const p of t.props) {
      if (isStringEnum(p.schema)) enums.set(enumTypeName(t.name, p.name), p.schema.enum.slice());
    }
  }
  return enums;
}

// --- per-language scalar resolvers (non-enum) --------------------------------

function rustType(s) {
  s = nonNullSchema(s);
  const r = refName(s); if (r) return r;
  switch (s.type) {
    case "string": return "String";
    case "integer": return "i64";
    case "number": return "f64";
    case "boolean": return "bool";
    case "array": return `Vec<${rustType(s.items || {})}>`;
    default: return "serde_json::Value";
  }
}
function tsType(s) {
  s = nonNullSchema(s);
  const r = refName(s); if (r) return r;
  switch (s.type) {
    case "string": return "string";
    case "integer": case "number": return "number";
    case "boolean": return "boolean";
    case "array": return `${tsType(s.items || {})}[]`;
    default: return "Record<string, unknown>";
  }
}
function pyType(s) {
  s = nonNullSchema(s);
  const r = refName(s); if (r) return r;
  switch (s.type) {
    case "string": return "str";
    case "integer": return "int";
    case "number": return "float";
    case "boolean": return "bool";
    case "array": return `List[${pyType(s.items || {})}]`;
    default: return "dict";
  }
}
function goType(s) {
  s = nonNullSchema(s);
  const r = refName(s); if (r) return r;
  switch (s.type) {
    case "string": return "string";
    case "integer": return "int64";
    case "number": return "float64";
    case "boolean": return "bool";
    case "array": return `[]${goType(s.items || {})}`;
    default: return "map[string]any";
  }
}
function dartType(s) {
  s = nonNullSchema(s);
  const r = refName(s); if (r) return r;
  switch (s.type) {
    case "string": return "String";
    case "integer": return "int";
    case "number": return "double";
    case "boolean": return "bool";
    case "array": return `List<${dartType(s.items || {})}>`;
    default: return "Map<String, Object?>";
  }
}

// --- emitters: type[] -> { relpath: content } --------------------------------

// Shared Rust body renderer for both the plain `rust` crate and the wasm crate.
// `wasm` adds a `#[derive(Tsify)]` so wasm-pack emits a matching TypeScript
// `.d.ts`; the type bodies are otherwise identical, so the crates never drift.
// The wasm crate is DECLARATION-ONLY (no exported functions) so it deliberately
// omits `into_wasm_abi`/`from_wasm_abi`: those bake serde-wasm-bindgen's default
// map=JS-`Map` ABI into the type, which would contradict the `Record<..>` the
// `.d.ts` declares. A downstream crate that passes these across a real wasm
// boundary should add its own `#[wasm_bindgen]` fn + serializer config.
function renderRustBody(types, { wasm }) {
  const structDerive = wasm
    ? "#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]"
    : "#[derive(Debug, Clone, Serialize, Deserialize)]";
  const enumDerive = wasm
    ? "#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Tsify)]"
    : "#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]";
  const header = [`// ${BANNER}`, "", "use serde::{Deserialize, Serialize};"];
  if (wasm) header.push("use tsify::Tsify;");
  const out = [...header, ""];
  // Enums first.
  for (const [enumName, values] of collectEnums(types)) {
    out.push(enumDerive);
    out.push(`pub enum ${enumName} {`);
    for (const v of values) out.push(`    #[serde(rename = "${v}")]`, `    ${pascal(v)},`);
    out.push("}", "");
  }
  for (const t of types) {
    if (t.description) out.push(`/// ${cLine(t.description)}`);
    out.push(structDerive);
    out.push(`pub struct ${t.name} {`);
    for (const p of t.props) {
      if (p.description) out.push(`    /// ${cLine(p.description)}`);
      const ty = isStringEnum(p.schema) ? enumTypeName(t.name, p.name) : rustType(p.schema);
      const rustName = snake(p.name);
      const kw = RUST_KEYWORDS.has(rustName);
      const ident = kw ? `r#${rustName}` : rustName;
      if (kw || rustName !== p.name) out.push(`    #[serde(rename = "${p.name}")]`);
      // tsify's default TS for `serde_json::Value` is a bare (undefined) `Value`,
      // and for maps it emits `Map<..>` (wrong for JSON). Pin those fields to the
      // exact type the `typescript` emitter uses so the two TS surfaces agree.
      // Emitted adjacent to the field so it survives the optional serde attrs.
      const tsifyOverride = wasm && /serde_json::Value|BTreeMap/.test(ty)
        ? `    #[tsify(type = "${tsFieldType(p).replace(/"/g, '\\"')}")]`
        : null;
      if (p.required) {
        if (tsifyOverride) out.push(tsifyOverride);
        out.push(`    pub ${ident}: ${isNullable(p.schema) ? `Option<${ty}>` : ty},`);
      } else {
        out.push(`    #[serde(default, skip_serializing_if = "Option::is_none")]`);
        if (tsifyOverride) out.push(tsifyOverride);
        out.push(`    pub ${ident}: Option<${ty}>,`);
      }
    }
    out.push("}", "");
  }
  return out.join("\n");
}

function emitRust(types) {
  const cargo = `[package]
name = "canonical-interfaces"
version = "0.1.0"
edition = "2021"
description = "Generated typed payloads for the canonical.cloud API (see canonical-interfaces)."

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`;
  return { "rust/src/lib.rs": renderRustBody(types, { wasm: false }), "rust/Cargo.toml": cargo };
}

// Wasm build of the Rust types: same serde structs, plus tsify + wasm-bindgen so
// the payloads cross the JS/wasm boundary as real objects and a .d.ts is emitted.
// Kept in a separate crate (generated/rust-wasm) so the plain `rust` crate stays
// dependency-free. Build with: wasm-pack build generated/rust-wasm --target web
function emitRustWasm(types) {
  const cargo = `[package]
name = "canonical-interfaces-wasm"
version = "0.1.0"
edition = "2021"
description = "Generated typed payloads for the canonical.cloud API, compiled to WebAssembly (see canonical-interfaces)."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
tsify = { version = "0.5", features = ["js"] }
`;
  return { "rust-wasm/src/lib.rs": renderRustBody(types, { wasm: true }), "rust-wasm/Cargo.toml": cargo };
}

// The canonical TypeScript type for a field — shared by the `typescript` emitter
// and the `rust-wasm` tsify overrides so both TS surfaces stay identical.
function tsFieldType(p) {
  const base = isStringEnum(p.schema)
    ? nonNullSchema(p.schema).enum.map((v) => `"${v}"`).join(" | ")
    : tsType(p.schema);
  return isNullable(p.schema) ? `${base} | null` : base;
}

function emitTs(types) {
  const out = [`// ${BANNER}`, ""];
  for (const t of types) {
    if (t.description) out.push(`/** ${cBlock(t.description)} */`);
    out.push(`export type ${t.name} = {`);
    for (const p of t.props) {
      if (p.description) out.push(`  /** ${cBlock(p.description)} */`);
      const ty = tsFieldType(p);
      out.push(`  ${p.name}${p.required ? "" : "?"}: ${ty};`);
    }
    out.push("};", "");
  }
  return { "typescript/index.ts": out.join("\n") };
}

function emitPython(types) {
  const usesLiteral = types.some((t) => t.props.some((p) => isStringEnum(p.schema)));
  const typing = `from typing import List, Optional${usesLiteral ? ", Literal" : ""}`;
  const out = [`# ${BANNER}`, "from __future__ import annotations", "from dataclasses import dataclass", typing, ""];
  for (const t of types) {
    out.push("@dataclass", `class ${t.name}:`);
    if (t.description) out.push(`    """${pyDoc(t.description)}"""`);
    const ordered = [...t.props].sort((a, b) => Number(b.required) - Number(a.required));
    if (ordered.length === 0) out.push("    pass");
    for (const p of ordered) {
      const base = isStringEnum(p.schema)
        ? `Literal[${nonNullSchema(p.schema).enum.map((v) => `"${v}"`).join(", ")}]`
        : pyType(p.schema);
      const type = isNullable(p.schema) ? `Optional[${base}]` : base;
      out.push(p.required ? `    ${p.name}: ${type}` : `    ${p.name}: Optional[${base}] = None`);
    }
    out.push("");
  }
  return { "python/canonical_interfaces.py": out.join("\n") };
}

function emitGo(types) {
  const out = [`// ${BANNER}`, "", "package canonicalinterfaces", ""];
  for (const t of types) {
    if (t.description) out.push(`// ${t.name}: ${cLine(t.description)}`);
    out.push(`type ${t.name} struct {`);
    for (const p of t.props) {
      let doc = p.description ? cLine(p.description) : "";
      if (isStringEnum(p.schema)) doc = `${doc} (one of: ${p.schema.enum.join(", ")})`.trim();
      if (doc) out.push(`\t// ${doc}`);
      const ty = goType(p.schema); // enums are plain strings in Go
      const tag = p.required ? `json:"${p.name}"` : `json:"${p.name},omitempty"`;
      out.push(`\t${pascal(p.name)} ${p.required && !isNullable(p.schema) ? "" : "*"}${ty} \`${tag}\``);
    }
    out.push("}", "");
  }
  return { "go/interfaces.go": out.join("\n") };
}

// --- dart --------------------------------------------------------------------

// Dart has no structural types, so each $def becomes a `final class` with an
// explicit `fromJson`/`toJson` pair. Enum-valued fields stay `String` on the
// model (an unknown server value must not throw inside a Flutter app the way a
// strict Dart `enum` decode would); the permitted values are emitted alongside
// as constants so callers still get the vocabulary Rust and TypeScript get.
const dartIdent = (wireName) => {
  const name = camel(wireName);
  return DART_KEYWORDS.has(name) ? `${name}_` : name;
};
// A Dart-safe constant name for an enum *value* (e.g. "iso_27001" -> iso27001).
const dartConstName = (value) => {
  const name = camel(String(value).replace(/[^A-Za-z0-9_-]/g, "_"));
  const safe = /^[0-9]/.test(name) ? `v${name}` : name;
  return DART_KEYWORDS.has(safe) ? `${safe}_` : safe;
};

function dartDecode(schema, expr) {
  const s = nonNullSchema(schema);
  const r = refName(s);
  if (r) return `${r}.fromJson((${expr} as Map).cast<String, Object?>())`;
  switch (s.type) {
    case "string": return `${expr} as String`;
    case "integer": return `${expr} as int`;
    case "number": return `(${expr} as num).toDouble()`;
    case "boolean": return `${expr} as bool`;
    case "array": {
      const itemRef = refName(nonNullSchema(s.items || {}));
      return itemRef
        ? `(${expr} as List).map((value) => ${itemRef}.fromJson((value as Map).cast<String, Object?>())).toList(growable: false)`
        : `(${expr} as List).cast<${dartType(s.items || {})}>()`;
    }
    default: return `(${expr} as Map).cast<String, Object?>()`;
  }
}

// `nullable` drives `?.` so a required-but-nullable ref or list does not throw
// on encode. Scalars pass through untouched.
function dartEncode(schema, expr, nullable) {
  const s = nonNullSchema(schema);
  const access = nullable ? "?." : ".";
  if (refName(s)) return `${expr}${access}toJson()`;
  if (s.type === "array" && refName(nonNullSchema(s.items || {}))) {
    return `${expr}${access}map((value) => value.toJson()).toList(growable: false)`;
  }
  return expr;
}

function emitDart(types) {
  const out = [`// ${BANNER}`, ""];

  for (const [enumName, values] of collectEnums(types)) {
    out.push(`/// Permitted wire values for the fields typed as \`${enumName}\`.`);
    out.push(`abstract final class ${enumName} {`);
    const constNames = new Map();
    for (const v of values) {
      const c = dartConstName(v);
      if (constNames.has(c)) fail(`${enumName}: values "${v}" and "${constNames.get(c)}" both map to Dart constant "${c}"`);
      constNames.set(c, v);
      out.push(`  static const String ${c} = ${JSON.stringify(v)};`);
    }
    out.push(`  static const List<String> values = <String>[${values.map((v) => JSON.stringify(v)).join(", ")}];`);
    out.push("}", "");
  }

  for (const t of types) {
    // camelCasing two distinct wire names onto one Dart identifier would emit a
    // class that does not compile; fail loudly at generation time instead.
    const idents = new Map();
    for (const p of t.props) {
      const id = dartIdent(p.name);
      if (idents.has(id)) fail(`${t.source}:${t.name}: "${p.name}" and "${idents.get(id)}" both map to Dart identifier "${id}"`);
      idents.set(id, p.name);
    }

    if (t.description) out.push(`/// ${cLine(t.description)}`);
    out.push(`final class ${t.name} {`);
    // `required` tracks JSON Schema `required`, not nullability: a required
    // nullable field must still be passed explicitly (as null), matching the
    // non-omittable key TypeScript, Go, and serde all produce for it.
    out.push(`  const ${t.name}({${t.props.map((p) => `${p.required ? "required " : ""}this.${dartIdent(p.name)}`).join(", ")}});`);
    out.push("");

    for (const p of t.props) {
      let doc = p.description ? cLine(p.description) : "";
      if (isStringEnum(p.schema)) doc = `${doc} (one of: ${nonNullSchema(p.schema).enum.join(", ")})`.trim();
      if (doc) out.push(`  /// ${doc}`);
      const optional = !p.required || isNullable(p.schema);
      out.push(`  final ${dartType(p.schema)}${optional ? "?" : ""} ${dartIdent(p.name)};`);
    }

    out.push("");
    out.push(`  factory ${t.name}.fromJson(Map<String, Object?> json) => ${t.name}(`);
    for (const p of t.props) {
      const expr = `json[${JSON.stringify(p.name)}]`;
      // Guard whenever the value may legitimately be absent OR explicitly null:
      // `null as String` throws, so a required-but-nullable field needs it too.
      const guard = !p.required || isNullable(p.schema);
      const value = guard ? `${expr} == null ? null : ${dartDecode(p.schema, expr)}` : dartDecode(p.schema, expr);
      out.push(`    ${dartIdent(p.name)}: ${value},`);
    }
    out.push("  );", "");

    out.push("  Map<String, Object?> toJson() => {");
    for (const p of t.props) {
      const id = dartIdent(p.name);
      const optional = !p.required || isNullable(p.schema);
      const encoded = dartEncode(p.schema, id, optional);
      // Required-but-nullable keys stay present with an explicit null; only
      // genuinely optional keys are omitted, matching serde's skip_serializing_if.
      out.push(`    ${p.required ? "" : `if (${id} != null) `}${JSON.stringify(p.name)}: ${encoded},`);
    }
    out.push("  };", "}", "");
  }

  return {
    "dart/lib/canonical_interfaces.dart": out.join("\n"),
    // Compatibility shim: `generated/dart/lib/quote_v1.dart` was the whole Dart
    // surface before every type was emitted. Kept so existing imports resolve.
    "dart/lib/quote_v1.dart": [
      `// ${BANNER}`,
      "",
      "/// Deprecated path. The generated Dart surface now covers every schema type",
      "/// and lives in `canonical_interfaces.dart`; import that directly instead.",
      "export 'canonical_interfaces.dart';",
      "",
    ].join("\n"),
    "dart/pubspec.yaml": "name: canonical_interfaces\ndescription: Generated typed payloads for the canonical.cloud API.\nversion: 0.1.0\npublish_to: none\nenvironment:\n  sdk: '>=3.8.0 <4.0.0'\n",
  };
}

const EMITTERS = {
  rust: emitRust,
  "rust-wasm": emitRustWasm,
  typescript: emitTs,
  python: emitPython,
  go: emitGo,
  dart: emitDart,
  // TODO(client langs): ruby, java, csharp, php, elixir — one render fn each.
};

// --- run ---------------------------------------------------------------------

export function build() {
  const types = loadTypes();
  const files = {};
  for (const emit of Object.values(EMITTERS)) Object.assign(files, emit(types));
  return files;
}
export { loadTypes, pascal, snake, oneLine, refName, isNullable, isStringEnum, enumTypeName, collectEnums };

function main() {
  const check = process.argv.includes("--check");
  let files;
  try { files = build(); }
  catch (e) {
    if (e instanceof GenError) { console.error(`error: ${e.message}`); process.exit(2); }
    throw e;
  }
  let drift = 0;
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(genDir, rel);
    if (check) {
      const cur = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
      if (cur !== content) { console.error(`drift: ${rel}`); drift++; }
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
      console.log(`wrote ${rel}`);
    }
  }
  if (check && drift) { console.error(`${drift} file(s) out of date — run: node src/generate.mjs`); process.exit(1); }
  if (check) console.log("generated files up to date");
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main();
