// Generates and runs the per-language round-trip drivers.
//
// Each driver reads a fixture file of {name, type, json} cases on argv, decodes
// every case through the generated adapter for that language, re-encodes it,
// and prints one JSON line per case: {name, out}. The caller compares those
// against the input.
//
// Drivers are generated rather than committed so a new $def is covered the
// moment it exists in schema/index.json — a hand-maintained driver would drift
// into exactly the partial coverage this suite exists to catch.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

export const hasTool = (bin) => {
  try { execFileSync("sh", ["-c", `command -v ${bin}`], { stdio: "pipe" }); return true; }
  catch { return false; }
};

// --- dart --------------------------------------------------------------------

export function dartDriverSource(types, generatedDartFile) {
  const arms = types
    .map((t) => `    case '${t.name}':\n      return ${t.name}.fromJson(json).toJson();`)
    .join("\n");
  // The driver is written to a temp dir, so the generated library is imported
  // by absolute file: URI rather than a relative path.
  return `// Generated by tests/interface-conformance/drivers.mjs — do not edit.
import 'dart:convert';
import 'dart:io';
import '${pathToFileURL(generatedDartFile).href}';

Object? roundTrip(String type, Map<String, Object?> json) {
  switch (type) {
${arms}
  }
  throw ArgumentError('unknown type: \$type');
}

void main(List<String> args) {
  final cases = (jsonDecode(File(args[0]).readAsStringSync()) as List);
  for (final entry in cases) {
    final c = (entry as Map).cast<String, Object?>();
    final input = (c['json'] as Map).cast<String, Object?>();
    final out = roundTrip(c['type'] as String, input);
    stdout.writeln(jsonEncode({'name': c['name'], 'out': out}));
  }
}
`;
}

export function runDart(dir, types, fixtures, generatedDartFile) {
  const driver = path.join(dir, "dart_roundtrip.dart");
  const fixturePath = path.join(dir, "fixtures.json");
  fs.writeFileSync(driver, dartDriverSource(types, generatedDartFile));
  fs.writeFileSync(fixturePath, JSON.stringify(fixtures));
  const stdout = execFileSync("dart", ["run", driver, fixturePath], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  return parseLines(stdout);
}

// --- rust --------------------------------------------------------------------

export function rustDriverSource(types) {
  const arms = types
    .map((t) => `        "${t.name}" => serde_json::to_value(serde_json::from_value::<${t.name}>(input)?)?,`)
    .join("\n");
  return `// Generated by tests/interface-conformance/drivers.mjs — do not edit.
use canonical_interfaces::*;
use std::error::Error;

#[derive(serde::Deserialize)]
struct Case { name: String, r#type: String, json: serde_json::Value }

fn round_trip(kind: &str, input: serde_json::Value) -> Result<serde_json::Value, Box<dyn Error>> {
    Ok(match kind {
${arms}
        other => return Err(format!("unknown type: {other}").into()),
    })
}

fn main() -> Result<(), Box<dyn Error>> {
    let path = std::env::args().nth(1).ok_or("missing fixture path")?;
    let cases: Vec<Case> = serde_json::from_str(&std::fs::read_to_string(path)?)?;
    for case in cases {
        let out = round_trip(&case.r#type, case.json)?;
        println!("{}", serde_json::json!({"name": case.name, "out": out}));
    }
    Ok(())
}
`;
}

export function runRust(dir, types, fixtures, generatedRustDir) {
  const crate = path.join(dir, "rust-driver");
  fs.mkdirSync(path.join(crate, "src"), { recursive: true });
  fs.writeFileSync(path.join(crate, "src", "main.rs"), rustDriverSource(types));
  fs.writeFileSync(path.join(crate, "Cargo.toml"), `[package]
name = "conformance-driver"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
canonical-interfaces = { path = ${JSON.stringify(generatedRustDir)} }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[workspace]
`);
  const fixturePath = path.join(dir, "fixtures.json");
  fs.writeFileSync(fixturePath, JSON.stringify(fixtures));
  const stdout = execFileSync(
    "cargo",
    ["run", "--quiet", "--manifest-path", path.join(crate, "Cargo.toml"), "--", fixturePath],
    { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
  );
  return parseLines(stdout);
}

// --- shared ------------------------------------------------------------------

function parseLines(stdout) {
  const results = new Map();
  for (const line of stdout.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const parsed = JSON.parse(trimmed);
    results.set(parsed.name, parsed.out);
  }
  return results;
}
